baseURL = 'https://antwave.online/'
languageCode = 'es-es'
title = 'ANTWAVE.BLOG'
params.homeSubtitle = 'Time passes, people move. Like a river's flow, it never ends...'
params.gitUrl = 'https://github.com/antwave/antwave.github.io/commit/'
enableGitInfo = true

sectionPagesMenu = 'main'

[params.logo]
    logoMark     = ">"
    logoText     = "ANT.WAV"
    logoHomeLink = "https://antwave.online/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#eef525"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "3s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = false